Controllers/DrinksController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_SomerenProject.Models;
using MVC_SomerenProject.Repositories.DrinksRepo;
using MVC_SomerenProject.Repositories.StudentsRepo;
using static MVC_SomerenProject.Models.Drinks;

namespace MVC_SomerenProject.Controllers
{
    public class DrinksController : Controller
    {
        private readonly IDrinksRepository _drinksRepository;
        private readonly IStudentsRepository _studentsRepository;

        public DrinksController(IDrinksRepository drinksRepository, IStudentsRepository studentsRepository)
        {
            _drinksRepository = drinksRepository;
            _studentsRepository = studentsRepository;
        }

        public IActionResult Index()
        {
            var drinks = _drinksRepository.GetAllDrinks();
            var students = _studentsRepository.GetAll();

            ViewBag.Students = students ?? new List<Students>();

            return View(drinks);


        }



        // ADD DRINK
        [HttpGet]
        public IActionResult AddDrink()
        {

            return View();
        }
        [HttpPost]
        public IActionResult AddDrink(Drinks drink)
        {
            try
            {
                _drinksRepository.AddDrink(drink);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View(drink);
            }
        }



        // DELETE DRINK



        [HttpGet]
        public IActionResult DeleteDrink(int id)
        {
            var drink = _drinksRepository.GetDrinkById(id);
            if (drink == null)
            {
                return NotFound("Drink not found.");
            }
            return View(drink);
        }

        [HttpPost]
        public IActionResult DeleteDrink(Drinks drink)
        {
            try
            {


                _drinksRepository.DeleteDrink(drink);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View(drink);
            }
        }




        //  Order drink

        [HttpGet]
        public IActionResult OrderDrink(int id)
        {
            var student = _studentsRepository.GetById(id);
            if (student == null)
            {
                Console.WriteLine($"Error: No Student found with ID: {id}");
                return NotFound("Student not found.");
            }
            ViewBag.Drinks = _drinksRepository.GetAllDrinks();
            ViewBag.DrinkOrder = new DrinkOrder();
            return View(student);
        }
        [HttpPost]
        public IActionResult OrderDrink(Students students, int drinkId, int quantity, string confirmation)
        {
            if (confirmation == "no")
            {
                return RedirectToAction("Index");
            }
            var drinkOrder = new DrinkOrder { StudentNumber = students.StudentNumber, DrinkId = drinkId, Quantity = quantity };
            try
            {
                _drinksRepository.OrderDrink(drinkOrder);

                ViewBag.Drinks = _drinksRepository.GetAllDrinks();
                ViewBag.DrinkOrder = new DrinkOrder();
                return View(students);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);

                ViewBag.Drinks = _drinksRepository.GetAllDrinks();
                ViewBag.DrinkOrder = new DrinkOrder();
                return View(students);
            }
        }
    }

}

Controllers/LecturersController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_SomerenProject.Models;
using MVC_SomerenProject.Repositories.LecturersRepo;

namespace MVC_SomerenProject.Controllers
{
	public class LecturersController : Controller
	{
		private readonly ILecturersRepository _lecturersRepository;

		public LecturersController(ILecturersRepository lecturersRepository)
		{
			_lecturersRepository = lecturersRepository;
		}


		public IActionResult Index()
		{
			List<Lecturers> lecturers = _lecturersRepository.GetAll();
			if (lecturers == null || lecturers.Count == 0)
			{
				return View(new List<Lecturers>()); 
			}
			return View(lecturers);
		}

		
		[HttpGet]
		public ActionResult Add()
		{
			return View("CreateLecturer");
		}

		[HttpPost]
		public IActionResult Add(Lecturers lecturers)
		{
			try
			{
				_lecturersRepository.Add(lecturers);
				return View("CreateLecturer", lecturers);
			}
			catch
			{
				return BadRequest(new { message = "Lecturer Is Not added" });
			}

		}

		[HttpGet]
		public ActionResult Edit(int? Id)
		{
			if (Id == null)
			{
				return NotFound();
			}
			
			Lecturers? lecturers = _lecturersRepository.GetById((int)Id);
			return View("EditLecturer", lecturers);
		}

		 
		[HttpPost]
		public ActionResult Edit(Lecturers lecturers)
		{
			try
			{ 
				_lecturersRepository.Update(lecturers);
				return RedirectToAction("Index");
			}
			catch (Exception ex)
			{
				return View("EditLecturer", lecturers);
			}
		}

		
		[HttpGet]
		public ActionResult Delete(int? Id)
		{
			if (Id == null)
			{
				return NotFound();
			}

			Lecturers? lecturers = _lecturersRepository.GetById((int)Id);
			return View("DeleteLecturer", lecturers);
		}

		 
		[HttpPost]
		public ActionResult Delete(Lecturers lecturers)
		{
			try
			{
				_lecturersRepository.Delete(lecturers.LecturerNumber);
				return RedirectToAction("Index");
			}
			catch (Exception ex)
			{
				return View("DeleteLecturer", lecturers);
			}
		}
	}
}

Controllers/RoomsController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_SomerenProject.Models;
using MVC_SomerenProject.Repositories.RoomsRepo;

namespace MVC_SomerenProject.Controllers
{
	public class RoomsController : Controller
	{
		private readonly IRoomsRepository _roomsRepository;

		public RoomsController(IRoomsRepository roomsRepository)
		{
			_roomsRepository = roomsRepository;
		}


		public IActionResult Index()
		{
			List<Rooms> rooms = _roomsRepository.GetAll();
			if (rooms == null || rooms.Count == 0)
			{
				return View(new List<Rooms>()); 
			}
			return View(rooms);
		}

		 
		[HttpGet]
		public ActionResult Add()
		{
			return View("CreateRoom");
		}

		[HttpPost]
		public IActionResult Add(Rooms rooms)
		{
			try
			{
				_roomsRepository.Add(rooms);
				return View("CreateRoom", rooms);
			}
			catch
			{
				return BadRequest(new { message = "Room Is Not added" });
			}

		}

		[HttpGet]
		public ActionResult Edit(int? Id)
		{
			if (Id == null)
			{
				return NotFound();
			}
			
			Rooms? rooms = _roomsRepository.GetById((int)Id);
			return View("EditRoom", rooms);
		}


		[HttpPost]
		public ActionResult Edit(Rooms rooms)
		{
			try
			{ 
				_roomsRepository.Update(rooms); 
				return RedirectToAction("Index");
			}
			catch (Exception ex)
			{
				return View("EditRoom", rooms);
			}
		}

		[HttpGet]
		public ActionResult Delete(int? Id)
		{
			if (Id == null)
			{
				return NotFound();
			}

			Rooms? rooms = _roomsRepository.GetById((int)Id);
			return View("DeleteRoom", rooms);
		}

	
		[HttpPost]
		public ActionResult Delete(Rooms rooms)
		{
			try
			{
				_roomsRepository.Delete(rooms.RoomNumber); 
				return RedirectToAction("Index");
			}
			catch (Exception ex)
			{
				return View("DeleteRoom", rooms);
			}
		}
	}
}

Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_SomerenProject.Models;
using MVC_SomerenProject.Repositories.StudentsRepo;

namespace MVC_SomerenProject.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IStudentsRepository _studentsRepository;

        public StudentsController(IStudentsRepository studentRepository)
        {
            _studentsRepository = studentRepository;
        }

    
        public IActionResult Index()
        {
            List<Students> students = _studentsRepository.GetAll();
            if (students == null || students.Count == 0)
            {
                return View(new List<Students>()); // Return empty list instead of null
            }
            return View(students);
        }

         
        [HttpGet]
        public ActionResult Add()
        {
            return View("CreateStudent");
        }

       [HttpPost]
        public IActionResult Add(Students student)
        {
            try
            {
                _studentsRepository.Add(student);
                return View("CreateStudent", student);

            }
            catch
            {
                return BadRequest(new { message = "Student Is Not added" });
            }

        }

        
        [HttpGet]
        public ActionResult Edit(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            //Get students via repository 
            Students? students = _studentsRepository.GetById((int)Id);
            return View("EditStudent", students);
        }

        
        [HttpPost]
        public ActionResult Edit(Students students)
        {
            try
            {
                //update via repository 
                _studentsRepository.Update(students);

                //go back to list (via Index) 
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                //something's wrong, go back to view 
                return View("EditStudent", students);
            }
        }

        
        [HttpGet]
        public ActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            
            Students? students = _studentsRepository.GetById((int)Id);
            return View("DeleteStudent", students);
        }

        
        [HttpPost]
        public ActionResult Delete(Students students)
        {
            try
            {
                _studentsRepository.Delete(students.StudentNumber); 
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            { 
                return View("DeleteStudent", students);
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_SomerenProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_SomerenProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_SomerenProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lecturers" asp-action="Index">Lecturers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Drinks" asp-action="Index">Drinks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Activities" asp-action="Index">Activities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MVC_SomerenProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>